### PR TITLE
[DEV] parameters populate

### PR DESCRIPTION
**Pull request by Mxrcon**
# Parameter populate
Hey, I'm suggesting this PR with new parameters for the modules, and adding them with the standard values, I'll add the execution options like `--quiet` on another PR 

Feel free to make any necessary changes, and discuss those changes in the comments of this PR, I'm at your disposal.

Warmly, Davi

### CODE REVIEW

**Comment by Mxrcon** [comment]
aiming to solve https://github.com/emilyncosta/mtbseq-nf/issues/9#issuecomment-882989051

**Review by abhi18av — CHANGES_REQUESTED** [review]
Okay, this is getting there.

Though, it only covers one use case so far, when the user doesn't mention any global parameters, when the module is run it takes the module-level parameters.

What we need to add is a global parameter location, which can be used to override the module level parameters, please refer https://github.com/seqeralabs/gatk4-germline-snps-indels/blob/4eee70d85b355a9c317e5e8e1888f87745304c05/nextflow.config#L14 for grouping these paramters in a hash-map for the module name. 

And this https://github.com/seqeralabs/gatk4-germline-snps-indels/blob/4eee70d85b355a9c317e5e8e1888f87745304c05/workflows/preprocessing_mapping/preprocessing_mapping.nf#L23 for importing these parameters.

**Comment by Mxrcon** [comment]
Oh, true! I'll add this new layer of params declaration and them add it here! Thanks for your review!

**Comment by Mxrcon** [comment]
Hey @abhi18av I've added a new layer and a config file named `global_params` that has been included on the nextflow config. I'm tempted to create a new PR to cleanup the configuration and add the standard ones from our other projects, what do you think?

**Review by abhi18av — APPROVED** [review]
Looks good to merge ✅ 

> Hey @abhi18av I've added a new layer and a config file named global_params that has been included on the nextflow config. I'm tempted to create a new PR to cleanup the configuration and add the standard ones from our other projects, what do you think?

I think we should atleast track this in another issue and then maybe, address this later after a bit of testing ourselves.

**Comment by Mxrcon** [comment]
>  address this later after a bit of testing ourselves
yes, sure! Thank you!

**Pull request merged**
