### PR TITLE
Globals params and real world testing

### PR DESCRIPTION
**Pull request by abhi18av**

### CODE REVIEW

**Comment by Mxrcon** [comment]
Hey @abhi18av I've checked your tests and they seem to be going very well, :rocket: hope to see this PR merged!

**Comment by abhi18av** [comment]
Thanks @Mxrcon :)

This has been a great experience overall - thanks for the initial groundwork. I had to change ~30/40 % but that was always expected.

Through this PR, I've experimented with a per-push trigger (Github action) as a means for instant feedback, overall it has been a good experience. This is also the reason for so many commits 😉 

Once the PR is in a reasonable state, I'll request you to give a look to share your thoughts and also to take notes on why I made certain choices.

**Comment by Mxrcon** [comment]
Yes! I've tracked some of you changes and I'm understanding the design path that you decided to use and totally agreed with, on the pr I'll give a more detailed look and will be happy to share my thoughts.

**Comment by abhi18av** [comment]
I've now been successfull in testing end to end the entire workflow.

https://tower.nf/orgs/BioSharp_OU/workspaces/Davi_Internship/watch/5FOe4rEtKrPbCw

https://tower.nf/orgs/BioSharp_OU/workspaces/Davi_Internship/watch/5qa1ccl56cMe47

For the `TBFull` module, the minimum infra for 2 genomes should be `5_CPU/16_MEM`

**Comment by abhi18av** [comment]
@Mxrcon , I've opened this up for discussion/review now. 

I'd be happy to discuss the design choices and accomodate change requests :)

**Comment by Mxrcon** [comment]
The changes seems to fix the linked issues, and all of them are inside what we discussed about the exit messages. I've saw the messages on the Tower result and they also seem fine, but I'd like to request acess to the output if possible, and try to get in touch with the real results of our work.

**Comment by abhi18av** [comment]
>  I'd like to request acess to the output if possible, and try to get in touch with the real results of our work.

This isn't possible unfortunately since I used a temp k8s cluster for developing and testing this and then the server was deleted 😅

**Pull request merged**
